[project]
name = 'Stacks-money'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.Stacks-Money]
path = 'contracts/Stacks-Money.clar'
clarity_version = 4
epoch = "latest"
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
